[package]
name = "rust_lib_libgodot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
android_logger = "0.15.1"
flutter_logger = "0.6.1"
flutter_rust_bridge = "=2.11.1"
godot = {version = "0.4.2", features = ["api-custom-json", "__debug-log"]}
jni = "0.21.1"
libc = "0.2.177"
libloading = "0.8.9"
log = "0.4.28"

[build-dependencies]
bindgen = "0.71.0"
anyhow = "1.0.100"
zip = "6.0.0"
reqwest = "0.12.24"
cached-path = "0.9.0"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
